Switch to open policy agent to replace conftest

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -109,9 +109,19 @@ jobs:
           version: latest    
       
       - name: Run OPA Policy Check
+        id: opa_eval
+        if: steps.terraform_plan.conclusion == 'success'
         run: |
           terraform show -json tfplan.binary | grep '^{.*}$' > tfplan.json
-          opa eval --format pretty --input tfplan.json --data policy 'data.terraform.analysis.deny'    
+          result=$(opa eval --format json --input tfplan.json --data policy 'data.terraform.analysis.deny')
+          echo "OPA evaluation result: $result"
+          count=$(echo "$result" | jq '[.[].expressions[].value] | flatten | length')
+          if [ "$count" -gt 0 ]; then
+            echo "❌ OPA Deny policy failed with $count violation(s)."
+            exit 1
+          else
+            echo "✅ No deny violations found."
+          fi    
 
       - name: Run OPA Tests
         id: opa_tests
